name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ttank-webapp-g15
  AZURE_RG: rg-thinktank-g15
  ACR_NAME: thinktankregistry
  IMAGE_NAME: thinktankcli:latest
  CONTAINER_PORT: 8080

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name $ACR_NAME

      - name: Build and Push Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RG \
            --docker-custom-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME \
            --docker-registry-server-url https://$ACR_NAME.azurecr.io

      - name: Restart Web App
        run: |
          az webapp restart \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RG
